//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es_ES() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SitioWebOasis.Language.es-ES", typeof(es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string BC_INICIO {
            get {
                return ResourceManager.GetString("BC_INICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR.
        /// </summary>
        public static string BTN_GUARDAR {
            get {
                return ResourceManager.GetString("BTN_GUARDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR EVALUCIÓN ACUMULATIVA.
        /// </summary>
        public static string BTN_GUARDAR_EVALUACION_ACUMULATIVA {
            get {
                return ResourceManager.GetString("BTN_GUARDAR_EVALUACION_ACUMULATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR EVALUACIÓN FINAL.
        /// </summary>
        public static string BTN_GUARDAR_EVALUACION_FINAL {
            get {
                return ResourceManager.GetString("BTN_GUARDAR_EVALUACION_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR EVALUACIÓN RECUPERACION.
        /// </summary>
        public static string BTN_GUARDAR_EVALUACION_RECUPERACION {
            get {
                return ResourceManager.GetString("BTN_GUARDAR_EVALUACION_RECUPERACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GESTIÓN DE NOTAS.
        /// </summary>
        public static string DOC_GESTION_NOTAS {
            get {
                return ResourceManager.GetString("DOC_GESTION_NOTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVALUACIÓN FORMATIVA.
        /// </summary>
        public static string DOC_GRD_EVALUACION_FORMATIVA {
            get {
                return ResourceManager.GetString("DOC_GRD_EVALUACION_FORMATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ASIGNATURAS.
        /// </summary>
        public static string DOC_LBL_ASIGNATURAS {
            get {
                return ResourceManager.GetString("DOC_LBL_ASIGNATURAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        public static string DOC_TB_COL_ACCION {
            get {
                return ResourceManager.GetString("DOC_TB_COL_ACCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        public static string DOC_TB_COL_ASIGNATURA {
            get {
                return ResourceManager.GetString("DOC_TB_COL_ASIGNATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string DOC_TB_COL_NIVEL {
            get {
                return ResourceManager.GetString("DOC_TB_COL_NIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No..
        /// </summary>
        public static string DOC_TB_COL_NUMERO {
            get {
                return ResourceManager.GetString("DOC_TB_COL_NUMERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paralelo.
        /// </summary>
        public static string DOC_TB_COL_PARALELO {
            get {
                return ResourceManager.GetString("DOC_TB_COL_PARALELO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parcial Activo.
        /// </summary>
        public static string DOC_TB_COL_PARCIAL_ACTIVO {
            get {
                return ResourceManager.GetString("DOC_TB_COL_PARCIAL_ACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promedio General.
        /// </summary>
        public static string DOC_TB_COL_PROMEDIO_GENERAL {
            get {
                return ResourceManager.GetString("DOC_TB_COL_PROMEDIO_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rendimiento académico.
        /// </summary>
        public static string DOC_TB_COL_RENDIMIENTO_ACADEMICO {
            get {
                return ResourceManager.GetString("DOC_TB_COL_RENDIMIENTO_ACADEMICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVALUACIÓN ACUMULATIVA.
        /// </summary>
        public static string DOC_TB_EV_ACUMULATIVA {
            get {
                return ResourceManager.GetString("DOC_TB_EV_ACUMULATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVALUACIÓN FINAL.
        /// </summary>
        public static string DOC_TB_EV_FINAL {
            get {
                return ResourceManager.GetString("DOC_TB_EV_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVALUACIÓN RECUPERACIÓN.
        /// </summary>
        public static string DOC_TB_EV_RECUPERACION {
            get {
                return ResourceManager.GetString("DOC_TB_EV_RECUPERACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESPOCH - DTIC - 2017.
        /// </summary>
        public static string DTIC {
            get {
                return ResourceManager.GetString("DTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información &apos;no&apos; disponible.
        /// </summary>
        public static string EST_DE_DATOS_USUARIO_NO_DISPONIBLE {
            get {
                return ResourceManager.GetString("EST_DE_DATOS_USUARIO_NO_DISPONIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CALLE PRINCIPAL.
        /// </summary>
        public static string EST_DG_CALLE_PRINCIPAL {
            get {
                return ResourceManager.GetString("EST_DG_CALLE_PRINCIPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CALLE SECUNDARIA.
        /// </summary>
        public static string EST_DG_CALLE_SECUNDARIA {
            get {
                return ResourceManager.GetString("EST_DG_CALLE_SECUNDARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANTON.
        /// </summary>
        public static string EST_DG_CANTON {
            get {
                return ResourceManager.GetString("EST_DG_CANTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CORREO ELECTRONICO INSTITUCIONAL.
        /// </summary>
        public static string EST_DG_CORREO_INSTITUCIONAL {
            get {
                return ResourceManager.GetString("EST_DG_CORREO_INSTITUCIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CORREO PERSONAL.
        /// </summary>
        public static string EST_DG_CORREO_PERSONAL {
            get {
                return ResourceManager.GetString("EST_DG_CORREO_PERSONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DATOS PERSONALES DEL ESTUDIANTE.
        /// </summary>
        public static string EST_DG_DATOS {
            get {
                return ResourceManager.GetString("EST_DG_DATOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECCIÓN.
        /// </summary>
        public static string EST_DG_DIRECCION {
            get {
                return ResourceManager.GetString("EST_DG_DIRECCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESTADO CIVIL.
        /// </summary>
        public static string EST_DG_ESTADO_CIVIL {
            get {
                return ResourceManager.GetString("EST_DG_ESTADO_CIVIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ETNIA.
        /// </summary>
        public static string EST_DG_ETNIA {
            get {
                return ResourceManager.GetString("EST_DG_ETNIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA NACIMIENTO.
        /// </summary>
        public static string EST_DG_FECHA_NACIMIENTO {
            get {
                return ResourceManager.GetString("EST_DG_FECHA_NACIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GENERO.
        /// </summary>
        public static string EST_DG_GENERO {
            get {
                return ResourceManager.GetString("EST_DG_GENERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NACIONALIDAD.
        /// </summary>
        public static string EST_DG_NACIONALIDAD {
            get {
                return ResourceManager.GetString("EST_DG_NACIONALIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRES.
        /// </summary>
        public static string EST_DG_NOMBRES {
            get {
                return ResourceManager.GetString("EST_DG_NOMBRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUMERO DE CASA.
        /// </summary>
        public static string EST_DG_NUMERO_CASA {
            get {
                return ResourceManager.GetString("EST_DG_NUMERO_CASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUMERO DE IDENTIFICACION.
        /// </summary>
        public static string EST_DG_NUMERO_IDENTIFICACION {
            get {
                return ResourceManager.GetString("EST_DG_NUMERO_IDENTIFICACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PAIS.
        /// </summary>
        public static string EST_DG_PAIS {
            get {
                return ResourceManager.GetString("EST_DG_PAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARROQUIA.
        /// </summary>
        public static string EST_DG_PARROQUIA {
            get {
                return ResourceManager.GetString("EST_DG_PARROQUIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a apellido materno.
        /// </summary>
        public static string EST_DG_PH_APELLIDO_MATERNO {
            get {
                return ResourceManager.GetString("EST_DG_PH_APELLIDO_MATERNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a apellido paterno.
        /// </summary>
        public static string EST_DG_PH_APELLIDO_PATERNO {
            get {
                return ResourceManager.GetString("EST_DG_PH_APELLIDO_PATERNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electronico personal.
        /// </summary>
        public static string EST_DG_PH_CORREO_PERSONAL {
            get {
                return ResourceManager.GetString("EST_DG_PH_CORREO_PERSONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres completos.
        /// </summary>
        public static string EST_DG_PH_NOMBRES {
            get {
                return ResourceManager.GetString("EST_DG_PH_NOMBRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de indentificación (cedula de ciudadania / pasaporte).
        /// </summary>
        public static string EST_DG_PH_NUMERO_IDENTIFICACION {
            get {
                return ResourceManager.GetString("EST_DG_PH_NUMERO_IDENTIFICACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de teléfono convencional.
        /// </summary>
        public static string EST_DG_PH_TELEFONO_FIJO {
            get {
                return ResourceManager.GetString("EST_DG_PH_TELEFONO_FIJO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de teléfono celular.
        /// </summary>
        public static string EST_DG_PH_TELEFONO_MOVIL {
            get {
                return ResourceManager.GetString("EST_DG_PH_TELEFONO_MOVIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRIMER APELLIDO.
        /// </summary>
        public static string EST_DG_PRIMER_APELLIDO {
            get {
                return ResourceManager.GetString("EST_DG_PRIMER_APELLIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROVINCIA.
        /// </summary>
        public static string EST_DG_PROVINCIA {
            get {
                return ResourceManager.GetString("EST_DG_PROVINCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REFERENCIA.
        /// </summary>
        public static string EST_DG_REFERENCIA {
            get {
                return ResourceManager.GetString("EST_DG_REFERENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGUNDO APELLIDO.
        /// </summary>
        public static string EST_DG_SEGUNDO_APELLIDO {
            get {
                return ResourceManager.GetString("EST_DG_SEGUNDO_APELLIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEXO.
        /// </summary>
        public static string EST_DG_SEXO {
            get {
                return ResourceManager.GetString("EST_DG_SEXO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TELEFONO FIJO.
        /// </summary>
        public static string EST_DG_TELEFONO_FIJO {
            get {
                return ResourceManager.GetString("EST_DG_TELEFONO_FIJO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TELEFONO MOVIL.
        /// </summary>
        public static string EST_DG_TELEFONO_MOVIL {
            get {
                return ResourceManager.GetString("EST_DG_TELEFONO_MOVIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIPO DE IDENTIFICACIÓN.
        /// </summary>
        public static string EST_DG_TIPO_IDENTIFICACION {
            get {
                return ResourceManager.GetString("EST_DG_TIPO_IDENTIFICACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIPO DE SANGRE.
        /// </summary>
        public static string EST_DG_TIPO_SANGRE {
            get {
                return ResourceManager.GetString("EST_DG_TIPO_SANGRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PDF.
        /// </summary>
        public static string EST_DWN_PDF {
            get {
                return ResourceManager.GetString("EST_DWN_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PDF - En blanco.
        /// </summary>
        public static string EST_DWN_PDF_BLANCO {
            get {
                return ResourceManager.GetString("EST_DWN_PDF_BLANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXCEL.
        /// </summary>
        public static string EST_DWN_XLS {
            get {
                return ResourceManager.GetString("EST_DWN_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobado.
        /// </summary>
        public static string EST_LBL_APROBADO {
            get {
                return ResourceManager.GetString("EST_LBL_APROBADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convalida.
        /// </summary>
        public static string EST_LBL_CONVALIDA {
            get {
                return ResourceManager.GetString("EST_LBL_CONVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVALUACIÓN ACUMULATIVA.
        /// </summary>
        public static string EST_LBL_EV_ACUMULATIVA {
            get {
                return ResourceManager.GetString("EST_LBL_EV_ACUMULATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVALUACIÓN FINAL.
        /// </summary>
        public static string EST_LBL_EV_FINAL {
            get {
                return ResourceManager.GetString("EST_LBL_EV_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVALUACIÓN RECUPERACIÓN.
        /// </summary>
        public static string EST_LBL_EV_RECUPERACION {
            get {
                return ResourceManager.GetString("EST_LBL_EV_RECUPERACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXONERADO.
        /// </summary>
        public static string EST_LBL_EXONERADO {
            get {
                return ResourceManager.GetString("EST_LBL_EXONERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horarios.
        /// </summary>
        public static string EST_LBL_HORARIOS {
            get {
                return ResourceManager.GetString("EST_LBL_HORARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horarios examenes.
        /// </summary>
        public static string EST_LBL_HORARIOS_EXAMENES {
            get {
                return ResourceManager.GetString("EST_LBL_HORARIOS_EXAMENES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string EST_LBL_NIVEL {
            get {
                return ResourceManager.GetString("EST_LBL_NIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas.
        /// </summary>
        public static string EST_LBL_NOTAS {
            get {
                return ResourceManager.GetString("EST_LBL_NOTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo académico.
        /// </summary>
        public static string EST_LBL_PERIODO_ACADEMICO {
            get {
                return ResourceManager.GetString("EST_LBL_PERIODO_ACADEMICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promedio.
        /// </summary>
        public static string EST_LBL_PROMEDIO {
            get {
                return ResourceManager.GetString("EST_LBL_PROMEDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reprobado.
        /// </summary>
        public static string EST_LBL_REPROBADO {
            get {
                return ResourceManager.GetString("EST_LBL_REPROBADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SIN REGISTROS DISPONIBLES.
        /// </summary>
        public static string EST_LBL_SIN_REGISTROS {
            get {
                return ResourceManager.GetString("EST_LBL_SIN_REGISTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalle.
        /// </summary>
        public static string EST_LBL_VER_MAS {
            get {
                return ResourceManager.GetString("EST_LBL_VER_MAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos estudiante.
        /// </summary>
        public static string EST_MN_DATOS_ESTUDIANTE {
            get {
                return ResourceManager.GetString("EST_MN_DATOS_ESTUDIANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horario estudiante.
        /// </summary>
        public static string EST_MN_HORARIO_ESTUDIANTE {
            get {
                return ResourceManager.GetString("EST_MN_HORARIO_ESTUDIANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horario examenes.
        /// </summary>
        public static string EST_MN_HORARIO_EXAMENES {
            get {
                return ResourceManager.GetString("EST_MN_HORARIO_EXAMENES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horarios.
        /// </summary>
        public static string EST_MN_HORARIOS {
            get {
                return ResourceManager.GetString("EST_MN_HORARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string EST_MN_INICIO {
            get {
                return ResourceManager.GetString("EST_MN_INICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matriculación.
        /// </summary>
        public static string EST_MN_MATRICULACION {
            get {
                return ResourceManager.GetString("EST_MN_MATRICULACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas estudiante.
        /// </summary>
        public static string EST_MN_NOTAS_ESTUDIANTE {
            get {
                return ResourceManager.GetString("EST_MN_NOTAS_ESTUDIANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favor vuelva a intentar, si el problema persiste consultar en secretaria de carrera.
        /// </summary>
        public static string EST_SMS_CONSULTA_SECRETARIA_CARRERA {
            get {
                return ResourceManager.GetString("EST_SMS_CONSULTA_SECRETARIA_CARRERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INFORMACIÓN REGISTRADA CORRECTAMENTE.
        /// </summary>
        public static string EST_SMS_REGISTRO_CORRECTO {
            get {
                return ResourceManager.GetString("EST_SMS_REGISTRO_CORRECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROBLEMA AL MOMENTO DE REALIZAR EL REGISTRO DE INFORMACIÓN.
        /// </summary>
        public static string EST_SMS_REGISTRO_INCORRECTO {
            get {
                return ResourceManager.GetString("EST_SMS_REGISTRO_INCORRECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acumulado.
        /// </summary>
        public static string EST_TB_COL_ACUMULADO {
            get {
                return ResourceManager.GetString("EST_TB_COL_ACUMULADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        public static string EST_TB_COL_ASIGNATURA {
            get {
                return ResourceManager.GetString("EST_TB_COL_ASIGNATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domingo.
        /// </summary>
        public static string EST_TB_COL_DOMINGO {
            get {
                return ResourceManager.GetString("EST_TB_COL_DOMINGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equivalencia.
        /// </summary>
        public static string EST_TB_COL_EQUIVALENCIA {
            get {
                return ResourceManager.GetString("EST_TB_COL_EQUIVALENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante.
        /// </summary>
        public static string EST_TB_COL_ESTUDIANTE {
            get {
                return ResourceManager.GetString("EST_TB_COL_ESTUDIANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha evaluación final.
        /// </summary>
        public static string EST_TB_COL_FECHA_EVALUACION_FINAL {
            get {
                return ResourceManager.GetString("EST_TB_COL_FECHA_EVALUACION_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha evaluación recuperación.
        /// </summary>
        public static string EST_TB_COL_FECHA_EVALUACION_RECUPERACION {
            get {
                return ResourceManager.GetString("EST_TB_COL_FECHA_EVALUACION_RECUPERACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        public static string EST_TB_COL_HORA {
            get {
                return ResourceManager.GetString("EST_TB_COL_HORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jueves.
        /// </summary>
        public static string EST_TB_COL_JUEVES {
            get {
                return ResourceManager.GetString("EST_TB_COL_JUEVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lunes.
        /// </summary>
        public static string EST_TB_COL_LUNES {
            get {
                return ResourceManager.GetString("EST_TB_COL_LUNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Martes.
        /// </summary>
        public static string EST_TB_COL_MARTES {
            get {
                return ResourceManager.GetString("EST_TB_COL_MARTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matricula.
        /// </summary>
        public static string EST_TB_COL_MATRICULA {
            get {
                return ResourceManager.GetString("EST_TB_COL_MATRICULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miercoles.
        /// </summary>
        public static string EST_TB_COL_MIERCOLES {
            get {
                return ResourceManager.GetString("EST_TB_COL_MIERCOLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string EST_TB_COL_NIVEL {
            get {
                return ResourceManager.GetString("EST_TB_COL_NIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota dos (2).
        /// </summary>
        public static string EST_TB_COL_NOTA_DOS {
            get {
                return ResourceManager.GetString("EST_TB_COL_NOTA_DOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota final.
        /// </summary>
        public static string EST_TB_COL_NOTA_FINAL {
            get {
                return ResourceManager.GetString("EST_TB_COL_NOTA_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota tres (3).
        /// </summary>
        public static string EST_TB_COL_NOTA_TRES {
            get {
                return ResourceManager.GetString("EST_TB_COL_NOTA_TRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota uno (1).
        /// </summary>
        public static string EST_TB_COL_NOTA_UNO {
            get {
                return ResourceManager.GetString("EST_TB_COL_NOTA_UNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No..
        /// </summary>
        public static string EST_TB_COL_NUMERO {
            get {
                return ResourceManager.GetString("EST_TB_COL_NUMERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación.
        /// </summary>
        public static string EST_TB_COL_OBSERVACION {
            get {
                return ResourceManager.GetString("EST_TB_COL_OBSERVACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ASISTENCIA (%).
        /// </summary>
        public static string EST_TB_COL_PORCIENTO_ASISTENCIA {
            get {
                return ResourceManager.GetString("EST_TB_COL_PORCIENTO_ASISTENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sabado.
        /// </summary>
        public static string EST_TB_COL_SABADO {
            get {
                return ResourceManager.GetString("EST_TB_COL_SABADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string EST_TB_COL_TOTAL {
            get {
                return ResourceManager.GetString("EST_TB_COL_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viernes.
        /// </summary>
        public static string EST_TB_COL_VIERNES {
            get {
                return ResourceManager.GetString("EST_TB_COL_VIERNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HORARIO ACADÉMICO.
        /// </summary>
        public static string EST_TB_HORARIO_ACADEMICO {
            get {
                return ResourceManager.GetString("EST_TB_HORARIO_ACADEMICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HORARIO EXAMENES.
        /// </summary>
        public static string EST_TB_HORARIO_EXAMENES {
            get {
                return ResourceManager.GetString("EST_TB_HORARIO_EXAMENES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVALUACIÓN FINAL.
        /// </summary>
        public static string LBL_CUMPLIMIENTO_EV_FINAL {
            get {
                return ResourceManager.GetString("LBL_CUMPLIMIENTO_EV_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXONERADO.
        /// </summary>
        public static string LBL_CUMPLIMIENTO_EXONERADO {
            get {
                return ResourceManager.GetString("LBL_CUMPLIMIENTO_EXONERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REPROBADO.
        /// </summary>
        public static string LBL_CUMPLIMIENTO_REPROBADO {
            get {
                return ResourceManager.GetString("LBL_CUMPLIMIENTO_REPROBADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REPROBADO - FALTAS.
        /// </summary>
        public static string LBL_CUMPLIMIENTO_REPROBADO_FALTAS {
            get {
                return ResourceManager.GetString("LBL_CUMPLIMIENTO_REPROBADO_FALTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ASIGNATURAS.
        /// </summary>
        public static string LST_LBL_ASIGNATURAS_DOCENTE {
            get {
                return ResourceManager.GetString("LST_LBL_ASIGNATURAS_DOCENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problema al generar archivo.
        /// </summary>
        public static string MSG_ERROR_GENERAR_ARCHIVO {
            get {
                return ResourceManager.GetString("MSG_ERROR_GENERAR_ARCHIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GESTION DE EVALUACION ACUMULATIVA CORRECTA.
        /// </summary>
        public static string MSG_REGISTRO_EV_ACUMULATIVA_CORRECTA {
            get {
                return ResourceManager.GetString("MSG_REGISTRO_EV_ACUMULATIVA_CORRECTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GESTION DE EVALUACION ACUMULATIVA PRESENTO INCONVENIENTE .
        /// </summary>
        public static string MSG_REGISTRO_EV_ACUMULATIVA_ERROR {
            get {
                return ResourceManager.GetString("MSG_REGISTRO_EV_ACUMULATIVA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTA_EV_ACUMULATIVA.
        /// </summary>
        public static string NF_EV_ACUMULATIVA {
            get {
                return ResourceManager.GetString("NF_EV_ACUMULATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTA_EV_FINAL.
        /// </summary>
        public static string NF_EV_FINAL {
            get {
                return ResourceManager.GetString("NF_EV_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTA_EV_RECUPERACION.
        /// </summary>
        public static string NF_EV_RECUPERACION {
            get {
                return ResourceManager.GetString("NF_EV_RECUPERACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cumplimiento.
        /// </summary>
        public static string NOTAS_TB_COL_CUMPLIMIENTO {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_CUMPLIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total acumulado.
        /// </summary>
        public static string NOTAS_TB_COL_EF_TOTAL_ACUMULADO {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_EF_TOTAL_ACUMULADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total asistencia(%).
        /// </summary>
        public static string NOTAS_TB_COL_EF_TOTAL_ASISTENCIA {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_EF_TOTAL_ASISTENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Ev. final.
        /// </summary>
        public static string NOTAS_TB_COL_EF_TOTAL_EV_FINAL {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_EF_TOTAL_EV_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota evaluación recuperación.
        /// </summary>
        public static string NOTAS_TB_COL_ER_NOTA_EV_RECUPERACION {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_ER_NOTA_EV_RECUPERACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total evaluación formativa.
        /// </summary>
        public static string NOTAS_TB_COL_ER_TOTAL_EV_FORMATIVA {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_ER_TOTAL_EV_FORMATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string NOTAS_TB_COL_ESTADO {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVALUACIÓN ACUMULATIVA.
        /// </summary>
        public static string NOTAS_TB_COL_EV_ACUMULATIVA {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_EV_ACUMULATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string NOTAS_TB_COL_NIVEL {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_NIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante.
        /// </summary>
        public static string NOTAS_TB_COL_NOMBRE_ESTUDIANTE {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_NOMBRE_ESTUDIANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota evaluación final.
        /// </summary>
        public static string NOTAS_TB_COL_NOTA_EV_FINAL {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_NOTA_EV_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string NOTAS_TB_COL_NUMERO {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_NUMERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matricula.
        /// </summary>
        public static string NOTAS_TB_COL_NUMERO_MATRICULA {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_NUMERO_MATRICULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de matricula.
        /// </summary>
        public static string NOTAS_TB_COL_NUMERO_MATRICULA_TOOL_TIP {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_NUMERO_MATRICULA_TOOL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación.
        /// </summary>
        public static string NOTAS_TB_COL_OBSERVACION {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_OBSERVACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota uno (1).
        /// </summary>
        public static string NOTAS_TB_COL_PARCIAL_01 {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_PARCIAL_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota dos (2).
        /// </summary>
        public static string NOTAS_TB_COL_PARCIAL_02 {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_PARCIAL_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota tres (3).
        /// </summary>
        public static string NOTAS_TB_COL_PARCIAL_03 {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_PARCIAL_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistencia (%).
        /// </summary>
        public static string NOTAS_TB_COL_PORCIENTO_ASISTENCIA {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_PORCIENTO_ASISTENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promedio.
        /// </summary>
        public static string NOTAS_TB_COL_PROMEDIO {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_PROMEDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promedio: Sumatoria de la Nota uno + Nota dos + Nota tres sobre (/) el numero de parcial vigente.
        /// </summary>
        public static string NOTAS_TB_COL_PROMEDIO_TOOL_TIP {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_PROMEDIO_TOOL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Acumulado.
        /// </summary>
        public static string NOTAS_TB_COL_TOTAL {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sumatoria: Nota uno + Nota dos + Nota tres.
        /// </summary>
        public static string NOTAS_TB_COL_TOTAL_TOOL_TIP {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_TOTAL_TOOL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTALIZADO EVALUACIÓN FORMATIVA.
        /// </summary>
        public static string NOTAS_TB_COL_TOTALIZADO_EV_FINAL {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_TOTALIZADO_EV_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTALIZADOS.
        /// </summary>
        public static string NOTAS_TB_COL_TOTALIZADOS {
            get {
                return ResourceManager.GetString("NOTAS_TB_COL_TOTALIZADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE CIUDAD.
        /// </summary>
        public static string PER_CB_CIUDAD_SELECCIONE {
            get {
                return ResourceManager.GetString("PER_CB_CIUDAD_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE ESTADO CIVIL.
        /// </summary>
        public static string PER_CB_EST_CIVIL_SELECCIONE {
            get {
                return ResourceManager.GetString("PER_CB_EST_CIVIL_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE ETNIA.
        /// </summary>
        public static string PER_CB_ETNIA_SELECCIONE {
            get {
                return ResourceManager.GetString("PER_CB_ETNIA_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE NACIONALIDAD.
        /// </summary>
        public static string PER_CB_NACIONALIDAD_SELECCIONE {
            get {
                return ResourceManager.GetString("PER_CB_NACIONALIDAD_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE PAIS.
        /// </summary>
        public static string PER_CB_PAIS_SELECCIONE {
            get {
                return ResourceManager.GetString("PER_CB_PAIS_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE PARROQUIA.
        /// </summary>
        public static string PER_CB_PARROQUIA_SELECCIONE {
            get {
                return ResourceManager.GetString("PER_CB_PARROQUIA_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE PROVINCIA.
        /// </summary>
        public static string PER_CB_PROVINCIA_SELECCIONE {
            get {
                return ResourceManager.GetString("PER_CB_PROVINCIA_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE SEXO.
        /// </summary>
        public static string PER_CB_SEXO_SELECCIONE {
            get {
                return ResourceManager.GetString("PER_CB_SEXO_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SIN REGISTROS DISPONIBLES.
        /// </summary>
        public static string PER_CB_SIN_VALOR_REGISTRADO {
            get {
                return ResourceManager.GetString("PER_CB_SIN_VALOR_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE TIPO DOCUMENTO.
        /// </summary>
        public static string PER_CB_TIPO_DOCUMENTO_SELECCIONE {
            get {
                return ResourceManager.GetString("PER_CB_TIPO_DOCUMENTO_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE TIPO DE SANGRE.
        /// </summary>
        public static string PER_CB_TIPO_SANGRE_SELECCIONE {
            get {
                return ResourceManager.GetString("PER_CB_TIPO_SANGRE_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DISCAPACIDAD.
        /// </summary>
        public static string PER_TITLE_DATOS_DISCAPACIDAD {
            get {
                return ResourceManager.GetString("PER_TITLE_DATOS_DISCAPACIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DATOS DE LOCALIZACIÓN.
        /// </summary>
        public static string PER_TITLE_DATOS_UBICACION {
            get {
                return ResourceManager.GetString("PER_TITLE_DATOS_UBICACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INFORMACIÓN GENERAL.
        /// </summary>
        public static string PER_TITLE_INFORMACION_GENERAL {
            get {
                return ResourceManager.GetString("PER_TITLE_INFORMACION_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LUGAR DE NACIMIENTO.
        /// </summary>
        public static string PER_TITLE_LUGAR_NACIMIENTO {
            get {
                return ResourceManager.GetString("PER_TITLE_LUGAR_NACIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema académico v3.8.1.
        /// </summary>
        public static string SA_VERSION {
            get {
                return ResourceManager.GetString("SA_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceder al Sistema Académico.
        /// </summary>
        public static string STR_ACCEDER_SISTEMA_ACADEMICO {
            get {
                return ResourceManager.GetString("STR_ACCEDER_SISTEMA_ACADEMICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string STR_CERRAR_SESION {
            get {
                return ResourceManager.GetString("STR_CERRAR_SESION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema academico - ESPOCH.
        /// </summary>
        public static string STR_FUENTE_REPORTE {
            get {
                return ResourceManager.GetString("STR_FUENTE_REPORTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HORARIO ACADEMICO.
        /// </summary>
        public static string STR_HORARIO_ACADEMICO {
            get {
                return ResourceManager.GetString("STR_HORARIO_ACADEMICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HORARIO EXAMENES.
        /// </summary>
        public static string STR_HORARIO_EXAMENES {
            get {
                return ResourceManager.GetString("STR_HORARIO_EXAMENES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESCUELA SUPERIOR POLITECNICA DE CHIMBORAZO.
        /// </summary>
        public static string STR_INSTITUCION {
            get {
                return ResourceManager.GetString("STR_INSTITUCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PERIODO ACADÉMICO.
        /// </summary>
        public static string STR_PERIODO_ACADEMICO {
            get {
                return ResourceManager.GetString("STR_PERIODO_ACADEMICO", resourceCulture);
            }
        }
    }
}
