//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWebOasis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://academicosil.espoch.edu.ec/DiscapacitadosNegociosWCF/Academico.asmx")]
        public string SitioWebOasis_WSAcademicoWCF_Academico {
            get {
                return ((string)(this["SitioWebOasis_WSAcademicoWCF_Academico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/OASis/OAS_AdministracionGeneral/AdministracionGeneral_BusinessSe" +
            "rvices/GestorAdministracionGeneral.asmx")]
        public string SitioWebOasis_WSAdministracionGeneral_GestorAdministracionGeneral {
            get {
                return ((string)(this["SitioWebOasis_WSAdministracionGeneral_GestorAdministracionGeneral"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Oasis/OAS_SitioWeb/SitioWeb_BusinessServices/DatosUsuarios.asmx")]
        public string SitioWebOasis_WSDatosUsuario_DatosUsuarios {
            get {
                return ((string)(this["SitioWebOasis_WSDatosUsuario_DatosUsuarios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Oasis/OAS_EgresamientoGraduacion/EgresamientoGraduacion_Business" +
            "Services/GestorEgresamientoGraduacion.asmx")]
        public string SitioWebOasis_WSEgresamientoGraduacion_GestorEgresamientoGraduacion {
            get {
                return ((string)(this["SitioWebOasis_WSEgresamientoGraduacion_GestorEgresamientoGraduacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Oasis/OAS_Evaluacion/Evaluacion_BusinessServices/GestordeReporte" +
            "s.asmx")]
        public string SitioWebOasis_WSGestorDeReportesEvaluacion_GestordeReportes {
            get {
                return ((string)(this["SitioWebOasis_WSGestorDeReportesEvaluacion_GestordeReportes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Oasis/OAS_Matriculacion/Matriculacion_BusinessServices/GestordeR" +
            "eportes.asmx")]
        public string SitioWebOasis_WSGestorDeReportesMatriculacion_GestordeReportes {
            get {
                return ((string)(this["SitioWebOasis_WSGestorDeReportesMatriculacion_GestordeReportes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Oasis/OAS_Evaluacion/Evaluacion_BusinessServices/GestorEvaluacio" +
            "n.asmx")]
        public string SitioWebOasis_WSGestorEvaluacion_GestorEvaluacion {
            get {
                return ((string)(this["SitioWebOasis_WSGestorEvaluacion_GestorEvaluacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Oasis/OAS_Comun/CommonWebServices/InfoCarreras.asmx")]
        public string SitioWebOasis_WSInfoCarreras_InfoCarreras {
            get {
                return ((string)(this["SitioWebOasis_WSInfoCarreras_InfoCarreras"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Oasis/OAS_SitioWeb/SitioWeb_BusinessServices/NotasEstudiante.asm" +
            "x")]
        public string SitioWebOasis_WSNotasEstudiante_NotasEstudiante {
            get {
                return ((string)(this["SitioWebOasis_WSNotasEstudiante_NotasEstudiante"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Oasis/OAS_SitioWeb/SitioWeb_BusinessServices/Seguridad.asmx")]
        public string SitioWebOasis_WSSeguridad_Seguridad {
            get {
                return ((string)(this["SitioWebOasis_WSSeguridad_Seguridad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/OASis/OAS_AdministracionCarrera/AdministracionCarrera_BusinessSe" +
            "rvices/GestorDefinicionPeriodo.asmx")]
        public string SitioWebOasis_WSGestorDefinicionPeriodoCarrera_GestorDefinicionPeriodo {
            get {
                return ((string)(this["SitioWebOasis_WSGestorDefinicionPeriodoCarrera_GestorDefinicionPeriodo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/OASis/OAS_AdministracionCarrera/AdministracionCarrera_BusinessSe" +
            "rvices/GestorAdministracionCarrera.asmx")]
        public string SitioWebOasis_WSAdministracionCarrera_GestorAdministracionCarrera {
            get {
                return ((string)(this["SitioWebOasis_WSAdministracionCarrera_GestorAdministracionCarrera"]));
            }
        }
    }
}
